# Generated by Django 5.0.6 on 2024-07-01 20:42

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('date_joined', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('last_login', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('is_admin', models.BooleanField(db_default=False)),
                ('is_staff', models.BooleanField(db_default=False)),
                ('is_active', models.BooleanField(db_default=False)),
                ('is_superadmin', models.BooleanField(db_default=False)),
                ('usid', models.CharField(editable=False, max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
